# Generated by Django 3.0.3 on 2020-04-19 05:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demoKLTN', '0002_auto_20200328_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cv',
            old_name='name',
            new_name='dateOfBirth',
        ),
        migrations.AddField(
            model_name='cv',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='fullName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='nameCv',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
