# Generated by Django 3.0.3 on 2020-04-19 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demoKLTN', '0003_auto_20200419_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
